<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MBOZDEMIR-NB" failures="1" tests="3" name="Personal Loan" time="0.073" errors="0" timestamp="2024-02-12T01:16:00 TRT">
  <testcase classname="test.day2" name="Demo" time="0.007"/>
  <testcase classname="test.day1" name="Demo" time="0.026">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.day1.Demo(day1.java:12)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="test.day1" name="SecondTest" time="0.001"/>
</testsuite> <!-- Personal Loan -->
